# filepath: /task_3/dbt_project/models/00_source/athena.yml
version: 2

models:
  - name: silver
    schema: silver_nome_sobrenome  # Altere para o schema correto da camada silver
    description: Camada silver do projeto, views intermediárias.
    tables:
      - name: produtos
        description: View de produtos na camada silver.
        columns:
          - name: codigo
            description: Código do produto.
          - name: ean
            description: Código EAN do produto.
          - name: descricao
            description: Descrição do produto.
          - name: preco_unitario
            description: Preço unitário do produto.
      - name: daily_sales
        description: View de vendas na camada silver.
        columns:
          - name: _id
            description: Identificador único da venda.
          - name: data
            description: Data da venda.
          - name: idsetor
            description: Identificador do setor.
          - name: codigo
            description: Código do produto (chave para dimensão produto).
          - name: ean
            description: Código EAN do produto.
          - name: descricao
            description: Descrição do produto.
          - name: quantidade
            description: Quantidade de itens vendidos.
          - name: valor_total
            description: Valor total da venda.
          - name: fl_produtopromocao
            description: Flag indicando se o produto estava em promoção.
          - name: quant_cupom_fiscal
            description: Quantidade de cupons fiscais.
          - name: preco_unitario
            description: Preço unitário do produto.
          - name: ano
            description: Ano da venda.
          - name: mes
            description: Mês da venda.