athena:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://mobiis-treinamento-cognitivo/dbt-athena-stage/
      region_name: us-east-2
      database: awsdatacatalog
      schema: dbt_nome_sobrenome # Replace with your name
      aws_profile_name: mobiis
      threads: 4